# 1. Read csv file

In [ ]:
#read a csv file
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/medcab9/ds/master/data/Cannabis%20StrainsFeatures%20-%20cannabis.csv")

df.head()

In [10]:
df.dtypes

Strain          object
Type            object
Rating         float64
Effects         object
Flavor          object
Description     object
dtype: object

In [11]:
df.isnull()

Strain   Type  Rating  Effects  Flavor  Description
0      False  False   False    False   False        False
1      False  False   False    False   False        False
2      False  False   False    False   False        False
3      False  False   False    False   False        False
4      False  False   False    False   False        False
...      ...    ...     ...      ...     ...          ...
2346   False  False   False    False   False        False
2347   False  False   False    False   False        False
2348   False  False   False    False   False        False
2349   False  False   False    False   False        False
2350   False  False   False    False   False        False

[2351 rows x 6 columns]

In [12]:
df.shape

(2351, 6)

In [13]:
df.describe()

Rating
count  2351.000000
mean      4.382561
std       0.639090
min       0.000000
25%       4.200000
50%       4.500000
75%       4.700000
max       5.000000

In [14]:
df.describe(include='all')

Strain    Type       Rating Effects Flavor Description
count        2351    2351  2351.000000    2351   2350        2350
unique       2350       3          NaN    1704   1349        2343
top     B-Witched  hybrid          NaN    None   None        None
freq            2    1212          NaN      29     44           5
mean          NaN     NaN     4.382561     NaN    NaN         NaN
std           NaN     NaN     0.639090     NaN    NaN         NaN
min           NaN     NaN     0.000000     NaN    NaN         NaN
25%           NaN     NaN     4.200000     NaN    NaN         NaN
50%           NaN     NaN     4.500000     NaN    NaN         NaN
75%           NaN     NaN     4.700000     NaN    NaN         NaN
max           NaN     NaN     5.000000     NaN    NaN         NaN

In [15]:
df.isnull().sum()

Strain         0
Type           0
Rating         0
Effects        0
Flavor         1
Description    1
dtype: int64

In [19]:
df['Strain'].value_counts()

B-Witched        2
Cookie-Jar       1
Key-Lime-Haze    1
Twista           1
Lamb-S-Bread     1
                ..
Pink-Pez         1
Odyssey          1
Old-Toby         1
Vcdc             1
Vanilla-Kush     1
Name: Strain, Length: 2350, dtype: int64

In [20]:
df['Rating'].unique()

array([4. , 4.7, 4.4, 4.2, 4.6, 4.5, 4.3, 5. , 3.8, 4.1, 4.8, 3.4, 3.7,
       3.9, 0. , 3. , 4.9, 3.6, 2.8, 3.3, 3.5, 3.2, 1. , 3.1, 2.5])

In [22]:
cols = ["Strain", 'Effects', 'Description', 'Flavor']
df['all_text'] = df[cols].apply(lambda row: '_'.join(row.values.astype(str)), axis=1)

In [23]:
df.head()

Strain    Type  Rating                                     Effects  \
0          100-Og  hybrid     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1  98-White-Widow  hybrid     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2            1024  sativa     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3        13-Dawgs  hybrid     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4        24K-Gold  hybrid     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   
1  The ‘98 Aloha White Widow is an especially pot...   
2  1024 is a sativa-dominant hybrid bred in Spain...   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   

                                            all_text  
0  100-Og_Creative,Energetic,Tingly,Euphoric,Rela...  
1  98-White-Widow_Relaxed,Aroused,Creative,Happy,...  
2  1024_Uplifted,Happy,Relaxed,Energetic,Creative...  
3  13-Dawgs_Tingly,Creative,Hungry,Relaxed,Uplift...  
4  24K-Gold_Happy,Relaxed,Euphoric,Uplifted,Talka...

# 2. Use Spacey to tokenize the total text

In [32]:
#use spacey to tokenize the total text
import re
import string

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import spacy
from spacy.tokenizer import Tokenizer
from bs4 import BeautifulSoup

In [25]:
#initialize spacy model and tokenizer
nlp = spacy.load("en_core_web_lg")
tokenizer = Tokenizer(nlp.vocab)

In [28]:
tokens =[]
#return lower case tokens and ignore stop words/punctunation

for doc in tokenizer.pipe(df['all_text'], batch_size=500):
    doc_tokens=[]
    
    for token in doc:
        #ignore stopwords, spaces and punctuation
        if (token.is_stop == False) & (token.is_punct == False) & (token.is_space == False):
            doc_tokens.append(token.text.lower())
    tokens.append(doc_tokens)
df['spacy_tokens'] = tokens
df['spacy_tokens'].head()

0    [100-og_creative,energetic,tingly,euphoric,rel...
1    [98-white-widow_relaxed,aroused,creative,happy...
2    [1024_uplifted,happy,relaxed,energetic,creativ...
3    [13-dawgs_tingly,creative,hungry,relaxed,uplif...
4    [24k-gold_happy,relaxed,euphoric,uplifted,talk...
Name: spacy_tokens, dtype: object

In [29]:
df.head()

Strain    Type  Rating                                     Effects  \
0          100-Og  hybrid     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1  98-White-Widow  hybrid     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2            1024  sativa     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3        13-Dawgs  hybrid     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4        24K-Gold  hybrid     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   
1  The ‘98 Aloha White Widow is an especially pot...   
2  1024 is a sativa-dominant hybrid bred in Spain...   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   

                                            all_text  \
0  100-Og_Creative,Energetic,Tingly,Euphoric,Rela...   
1  98-White-Widow_Relaxed,Aroused,Creative,Happy,...   
2  1024_Uplifted,Happy,Relaxed,Energetic,Creative...   
3  13-Dawgs_Tingly,Creative,Hungry,Relaxed,Uplift...   
4  24K-Gold_Happy,Relaxed,Euphoric,Uplifted,Talka...   

                                        spacy_tokens  
0  [100-og_creative,energetic,tingly,euphoric,rel...  
1  [98-white-widow_relaxed,aroused,creative,happy...  
2  [1024_uplifted,happy,relaxed,energetic,creativ...  
3  [13-dawgs_tingly,creative,hungry,relaxed,uplif...  
4  [24k-gold_happy,relaxed,euphoric,uplifted,talk...

# 3.  Vector Representation

In [33]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

In [34]:
def gather_data(df_column):
    """Produces list of documents form a df column
        returns lis of strings"""
    
    #data = []
    #for row in df_column:
    #    data.append(' '.join(str(row)))
    data = [''.join(str(item)) for item in df_column]
    
    return data

In [35]:
data = gather_data(df['spacy_tokens'])
data[0]

"['100-og_creative,energetic,tingly,euphoric,relaxed_$100', 'og', '50/50', 'hybrid', 'strain', 'packs', 'strong', 'punch.', 'supposedly', 'refers', 'strength', 'high', 'price', 'started', 'showing', 'hollywood.', 'plant,', '$100', 'og', 'tends', 'produce', 'large', 'dark', 'green', 'buds', 'stems.', 'users', 'report', 'strong', 'body', 'effect', 'indica', 'pain', 'relief', 'alert,', 'cerebral', 'feeling', 'thanks', 'sativa', 'side._earthy,sweet,citrus']"

In [36]:
#create the transformer
vect = CountVectorizer()

#build vocab
vect.fit(data)

#transform text
dtm = vect.transform(data)
dtm.shape

(2351, 12125)

In [38]:
vect.get_feature_names()

['00',
 '001_creative',
 '07',
 '09',
 '10',
 '100',
 '1024',
 '1024_uplifted',
 '10_relaxed',
 '10_talkative',
 '10th',
 '11',
 '115',
 '11_happy',
 '11_uplifted',
 '12',
 '120',
 '12_relaxed',
 '13',
 '1300',
 '13_happy',
 '13_relaxed',
 '14',
 '15',
 '16',
 '1600s',
 '17',
 '18',
 '18_relaxed',
 '19',
 '1900',
 '1957',
 '1960',
 '1960s',
 '1967',
 '1969',
 '1970',
 '1970s',
 '1973',
 '1974',
 '1974_relaxed',
 '1975',
 '1979',
 '1980',
 '1980s',
 '1985',
 '1986',
 '1988',
 '1989',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1993',
 '1994',
 '1996',
 '1997',
 '1998',
 '1999',
 '19th',
 '1_euphoric',
 '1_focused',
 '1_happy',
 '1_relaxed',
 '1st',
 '20',
 '2000',
 '2000s',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2010s',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '20_happy',
 '20_relaxed',
 '21',
 '22',
 '23',
 '24',
 '24k',
 '25',
 '26',
 '27',
 '27_euphoric',
 '28',
 '29',
 '2k',
 '2nd',
 '30',
 '300',
 '303',
 '32',


In [39]:
#tunning the parameter

#instantiate vectorizer object
tfidf = TfidfVectorizer(stop_words='english',
                        ngram_range=(1,2),
                        max_df=0.97,
                        min_df=3)
#create a vocabulary and get word counts per document
dtm = tfidf.fit_transform(data)

#get feature names to use a datafame column headers
dtm = pd.DataFrame(dtm.todense(), columns=tfidf.get_feature_names())

dtm.head()

09  09 cookies   10  10 11  10 feet  10 week  10 weeks       100  \
0  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.453982   
1  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.000000   
2  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.000000   
3  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.000000   
4  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.000000   

   100 sativa   11  ...  yunnan  zealand  zest  zestful  zesty  zesty lemon  \
0         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   
1         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   
2         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   
3         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   
4         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   

   zion  zion botanicals  zombie  zombie og  
0   0.0              0.0     0.0        0.0  
1   0.0              0.0     0.0        0.0  
2   0.0              0.0     0.0        0.0  
3   0.0              0.0     0.0        0.0  
4   0.0              0.0     0.0        0.0  

[5 rows x 9795 columns]

# 4. Train the model

In [40]:
from sklearn.neighbors import NearestNeighbors

#fit on TF-IDF Vectors
nn = NearestNeighbors(n_neighbors=5, algorithm='kd_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [42]:
#get the top 5 nearest neighbors
nn.kneighbors([dtm.iloc[0].values])

(array([[0.        , 1.29261968, 1.30504219, 1.31710642, 1.31788824]]),
 array([[   0,  682,  959, 1891,  237]]))

In [43]:
#wirte a fake review to test the model

fake_input = ["I'm looking for a strain that is going to help me relax when I study. I prefer a pepper flavor since it awakes me up and relaxes my muscles. I'm also looking for a bit of a pain relief and a dreamy sensation"]

In [44]:
fake_input

["I'm looking for a strain that is going to help me relax when I study. I prefer a pepper flavor since it awakes me up and relaxes my muscles. I'm also looking for a bit of a pain relief and a dreamy sensation"]

In [46]:
#print best matches

print("Recommendtion 1 --", df['all_text'][0])
print("Recommendtion 1 --", df['all_text'][682])

Recommendtion 1 -- 100-Og_Creative,Energetic,Tingly,Euphoric,Relaxed_$100 OG is a 50/50 hybrid strain that packs a strong punch. The name supposedly refers to both its strength and high price when it first started showing up in Hollywood. As a plant, $100 OG tends to produce large dark green buds with few stems. Users report a strong body effect of an indica for pain relief with the more alert, cerebral feeling thanks to its sativa side._Earthy,Sweet,Citrus
Recommendtion 1 -- Donna-Og_Creative,Euphoric,Relaxed,Happy,Hungry_Donna OG is a 50/50 hybrid cross between two OG varieties, resulting in a powerful strain with a sweet, pine aroma. Vector Beans of Cannagen Consulting in Los Angeles created Donna OG by combining Mary OG with Larry OG, and then backcrossing once again with a ML11 phenotype of the Mary OG. Donna OG blooms in purple hues, growing tightly and compactly under a blanket of THC-rich resin. Consumers can experience a wide spectrum of effects with Donna OG, including dreamy

In [47]:
#print a response in a dataframe
response = df[['Strain', 'Type', "Rating", "Effects", "Flavor", "Description"]].iloc[[411]]
response

Strain    Type  Rating                                   Effects  \
411  Butterscotch  indica     4.3  Relaxed,Euphoric,Focused,Creative,Sleepy   

                Flavor                                        Description  
411  Pine,Citrus,Nutty  Butterscotch is a treat of a strain that gets ...

In [50]:
response.to_json(orient='records')


'[{"Strain":"Butterscotch","Type":"indica","Rating":4.3,"Effects":"Relaxed,Euphoric,Focused,Creative,Sleepy","Flavor":"Pine,Citrus,Nutty","Description":"Butterscotch is a treat of a strain that gets its name from its distinctive candy aroma. This strong indica helps patients to gain some mental peace and unwind from a stressful day. Effects tend to be sedative and sleep-inducing, so Butterscotch is a good choice for treating insomnia."}]'

In [ ]:
import pickle
with open('k')